version: '3'

networks:
  dev:
    driver: bridge
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    container_name: iateccalendar.service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Database=iatec;Username=postgres;Password=postgres"
    networks:
      - dev
    restart: always
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8002:80"
    container_name: iateccalendar.webapp
    volumes:
      - ./IATEC.Calendar.WebApp/dist:/app/wwwroot

volumes:
  postgres_data:
