app = "iatec-calendar-postgres"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile.postgres"

[env]
  POSTGRES_DB = "meu_banco"
  POSTGRES_USER = "usuario"
  POSTGRES_PASSWORD = "senha"

[mounts]
  source = "data"
  destination = "/var/lib/postgresql/data"

[deploy]
  release_command = "echo 'Database has been deployed!'"
