app = "iatec-calendar-frontend"
primary_region = "gru"

[env]
  HOSTNAME = "0.0.0.0"

[build]
  dockerfile = "Dockerfile.frontend"

[[services]]
  deploy_strategy = "blue-green"

  http_checks = [
    { path = "/", interval = "10s", timeout = "60s", headers = { "Accept" = "text/html" } }
  ]  
  
  [http_service]
    internal_port = 8080
    force_https = false
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 1
    max_machines_running = 5
    
