# fly.toml app configuration file generated for iatec-calendar on 2024-10-13T11:57:35-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iatec-calendar'
primary_region = 'gru'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[build]
  image = "registry/backend:latest"

[build]
  image = "registry/frontend:latest"

[build]
  image = "registry/postgres:latest"
